In [2]:
import numpy as np

In [4]:
#Array of 10 zeros
arr = np.zeros(10)

In [6]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
arr5 = np.full(10,5)
arr5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [17]:
arr54 = np.linspace(10,50)
arr54

array([10.        , 10.81632653, 11.63265306, 12.44897959, 13.26530612,
       14.08163265, 14.89795918, 15.71428571, 16.53061224, 17.34693878,
       18.16326531, 18.97959184, 19.79591837, 20.6122449 , 21.42857143,
       22.24489796, 23.06122449, 23.87755102, 24.69387755, 25.51020408,
       26.32653061, 27.14285714, 27.95918367, 28.7755102 , 29.59183673,
       30.40816327, 31.2244898 , 32.04081633, 32.85714286, 33.67346939,
       34.48979592, 35.30612245, 36.12244898, 36.93877551, 37.75510204,
       38.57142857, 39.3877551 , 40.20408163, 41.02040816, 41.83673469,
       42.65306122, 43.46938776, 44.28571429, 45.10204082, 45.91836735,
       46.73469388, 47.55102041, 48.36734694, 49.18367347, 50.        ])

In [20]:
att_ev = np.arange(10,50,2)
att_ev

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [22]:
mat = np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
mat2 = np.eye(3).reshape(3,3)
mat2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.random.randn(1)

array([0.54880038])

In [29]:
np.random.randn(25)

array([ 0.2579607 , -0.67334998, -0.69828091,  0.38394286,  1.16372415,
        1.78080795,  0.87201392,  0.46510124,  0.03612612,  0.15756191,
        0.07627881,  0.9637489 ,  0.80929917, -0.54539506, -0.73042154,
        1.79501488,  0.13586584,  0.73807788, -0.09268389,  0.09079434,
        0.10230459, -1.04752183,  0.47615644,  0.14806187, -0.00246497])

In [31]:
np.linspace(0,1,25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [33]:
m = np.arange(1,26).reshape(5,5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
m.sum()

325

In [36]:
m.std()

7.211102550927978

In [37]:
m.sum(axis = 1)

array([ 15,  40,  65,  90, 115])